version: "3.4"

networks:
  apinetwork:
    driver: bridge

services:
  reservationsapi:
    image: reservationsapi
    build:
      context: .
      dockerfile: Reservations.Api/Dockerfile
    ports:
      - 5165:5165
    environment:
      - ConnectionStrings__SqliteConnection=Data Source=/app/data/reservationDB.db;Cache=Shared;Mode=ReadWriteCreate;
    networks:
      - apinetwork
    volumes:
      - ./data:/app/data


      
