# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

networks:
  apinetwork:
    driver: bridge

services:
  reservationsapi:
    image: reservationsapi
    build:
      context: .
      dockerfile: Reservations.Api/Dockerfile
    ports:
      - 5165:5165
    depends_on:
      - db-sqlserver
      - db-postgres


    networks:
      - apinetwork

  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=MyVeryStrongPassword123!
      - ACCEPT_EULA="Y"

    ports:
      - 1433:1433

  db-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=MyVeryStrongPassword123!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bookdb
    ports:
      - 5432:5432
    volumes:
      - postgres-dat:/var/lib/postgresql/data
    networks:
      - apinetwork

volumes:
  postgres-dat:
