# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

networks:
  mynetwork:
    driver: bridge

services:
  reservationsapi:
    image: reservationsapi
    build:
      context: .
      dockerfile: Reservations.Api/Dockerfile
    ports:
      - 5165:5165
    depends_on:
      - db-sqlserver
      - db-postgres


    networks:
      - mynetwork

  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=MyVeryStrongPassword123!
      - ACCEPT_EULA="Y"

    ports:
      - 1433:1433

  db-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=MyVeryStrongPassword123!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=reservationDB
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - 8080:80
    depends_on:
      - db-postgres
    networks:
      - mynetwork

volumes:
  postgres-data:
