version: "3.4"

networks:
  apinetwork:
    driver: bridge

services:
  reservationsapi:
    image: reservationsapi
    build:
      context: .
      dockerfile: Reservations.Api/Dockerfile
    ports:
      - 5165:5165
    environment:
      - ConnectionStrings__SqliteConnection=Data Source=reservationDB.db;
    networks:
      - apinetwork
    volumes:
      - ./:/app/data
    user: root
