global using Microsoft.EntityFrameworkCore;
global using Reservations.API.Model;
global using AutoMapper;
global using Reservations.API.DTO;
global using Reservations.Api.Data;
global using Reservations.Api.Services.Interfaces;
global using System.ComponentModel.DataAnnotations;
global using Reservations.Api.Middleware;
global using Reservations.Api.Profiles;
global using Reservations.Api.Services.Implementation;
global using Microsoft.AspNetCore.Mvc;
// global using Npgsql.EntityFrameworkCore.PostgreSQL;
